
# The Message Broker address is made up of port, Vhost path, and user/passwd like this:
# amqp://F1:F1@141.142.208.191:5672/%2fbunny
#
# In  order for this to work, a vhost named /bunny must be created on the
# RabbitMQ server. In addition, the user name/passwd pairs must also be
# configured and permissions added for /bunny in the RabbitMQ Mnesia database.
#
# Everything up until the '@' sign is handled by the Forwarder class, leaving
# the hostname or IP, plus the vhost like this:

# Unique identifiers
NCSA_BROKER_ADDR: 141.142.237.171:5672/%2fbunny
FQN: D1_DISTRIBUTOR
HOSTNAME: lsst-wf-dist01.ncsa.illinois.edu
IP_ADDR: 141.142.237.161

XFER_APP: scp
XFER_FILE: 16.7meg

CONSUME_QUEUE: D1_consume
PUBLISH_QUEUE: distributor_publish

SENTINEL_FILE: sentinel.fits
TARGET_DIR: /home/D1/xfer_dir/




